language: php

php:
  - 5.4
  - 5.5
  - hhvm

# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer install --prefer-source

script:
    - ./vendor/bin/phpcs --standard=psr2 src/
    - ./vendor/bin/phpunit -v --colors --coverage-text
